### ISSUE TITLE
Add content inside Readme.md file

### ISSUE THREAD

**Issue by ArunPatel02** [GDSCITM/GDSC-dataStore#6]
The content inside the readme file should contain : 
1 -> How to start fork repo
2-> How to push changes
3-> How to create a pull request

**Comment by munnokd** [comment]
Can I work on this issue?

**Comment by ArunPatel02** [comment]
> Can I work on this issue?

Yeah sure @munnokd thank you for showing your interest. Go ahead and let us know if you will need any help .
